resolver: nightly-2020-11-19

packages:
  - .

extra-deps:
  # - numhask-0.7.0.0
  - git: https://github.com/tonyday567/numhask.git
    commit: 82419e847e3a58aa0236b8e183d7485420989e69
  - protolude-0.3.0
  - random-1.2.0
  - splitmix-0.1.0.3
